extends SceneTree
const Cart = preload("res://scripts/ada_cart_adventure.gd")
var checks := 0
var failures := 0
func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok:
		failures += 1
		push_error(label)
func reject(cart: RefCounted, field: String, value: Variant) -> void:
	var before: Dictionary = cart.to_dict()
	var bad := before.duplicate(true)
	bad[field] = value
	check(not cart.load_dict(bad) and cart.to_dict() == before,"Atomic rejection: " + field)
func _initialize() -> void:
	var c := Cart.new()
	check(c.load_dict(JSON.parse_string(JSON.stringify(c.to_dict()))),"Default JSON roundtrip")
	check(not c.begin(false).ok and not c.begin(true,true).ok,"Recruitment/action gates")
	check(not c.choose_romance(true).ok,"No early romance")
	check(c.begin(true).ok and c.controlled_actor == "ada_cart","Begin grants cart control")
	check(not c.begin(true).ok and not c.confirm_routing().ok,"Lifecycle gates")
	check(c.inspect().ok and c.stage == "route_pressure","Inspection")
	check(not c.set_valve(-1,true).ok and not c.toggle_valve(3).ok,"Unknown valves")
	var wrong := c.confirm_routing()
	check(not wrong.ok and wrong.strain_delta == 1 and c.strain == 1,"Wrong route adds strain once per attempt")
	check(c.stage == "route_pressure" and c.status == "active","Wrong route stays retriable")
	c.set_valve(0,true)
	c.toggle_valve(2)
	check(c.valves == [true,false,true],"Authored pattern")
	var partial := c.to_dict()
	check(c.pause().ok and c.controlled_actor == "player","Pause returns control")
	check(not c.confirm_routing().ok and not c.resume(false).ok and not c.resume(true,true).ok,"Pause gates")
	check(c.resume(true).ok and c.valves == partial.valves and c.strain == 1,"Resume preserves work")
	check(c.confirm_routing().ok and c.stage == "drive","Route unlocks drive")
	check(not c.checkpoint_arrived(1).ok and not c.checkpoint_arrived(-1).ok,"Ordered arrivals")
	check(c.checkpoint_arrived(0).ok and not c.checkpoint_arrived(0).ok,"No duplicate arrival")
	check(c.checkpoint_arrived(1).ok,"Second arrival")
	var r := Cart.new()
	check(r.load_dict(JSON.parse_string(JSON.stringify(c.to_dict()))),"Mid-drive JSON restore")
	check(r.checkpoints == [0,1] and r.controlled_actor == "ada_cart","Restore progress/control")
	check(r.checkpoint_arrived(2).ok and r.stage == "return_to_camp","Third arrival unlocks return")
	check(not r.finish_at_camp(false).ok,"Must physically return")
	var finished := r.finish_at_camp(true)
	check(finished.ok and finished.completion.romance_required == false,"Separate nonromantic milestone")
	check(not r.finish_at_camp(true).ok and not r.romance_chosen,"One-time completion without forced romance")
	check(not r.choose_romance(false).ok and not r.romance_chosen,"Decline leaves romance unchanged")
	check(r.choose_romance(true).event == "mutual_kiss" and not r.choose_romance(true).ok,"Optional kiss once")
	check(c.load_dict(JSON.parse_string(JSON.stringify(r.to_dict()))) and not c.choose_romance(true).ok,"Kiss persists across restore")
	reject(c,"version",true)
	reject(c,"version",INF)
	reject(c,"strain",NAN)
	reject(c,"strain",-1)
	reject(c,"valves",[1,false,true])
	reject(c,"checkpoints",[0,0,2])
	reject(c,"checkpoints",[0,2,1])
	reject(c,"checkpoints",[false,1,2])
	reject(c,"controlled_actor","ada_cart")
	reject(c,"status","active")
	reject(c,"milestone_completed",false)
	reject(c,"romance_chosen",1)
	var fresh := Cart.new()
	reject(fresh,"romance_chosen",true)
	reject(fresh,"valves",[true,false,true])
	reject(fresh,"checkpoints",[0])
	if failures == 0: print("ADA CART ADVENTURE PASS: %d checks; route retry, ordered drive, save, milestone and optional romance" % checks)
	quit(1 if failures else 0)
