extends SceneTree
const Ada = preload("res://scripts/ada_companion.gd")
func _initialize() -> void:
	var ada := Ada.new()
	assert(not ada.invite(true).ok)
	assert(ada.meet() and not ada.meet() and ada.trust==5)
	ada.repair.set_vent(true)
	ada.repair.tick(3)
	ada.repair.recover_regulator()
	assert(ada.repair.install_regulator().ok)
	ada.repair.set_vent(false)
	ada.repair.set_feed(true)
	ada.repair.tick(3)
	ada.repair.set_feed(false)
	assert(ada.repair.test_machine().ok)
	var before := ada.to_dict()
	assert(not ada.invite(false).ok and ada.to_dict()==before)
	assert(ada.invite(true).ok and ada.trust==15)
	assert(not ada.invite(true).ok and ada.trust==15)
	var restored := Ada.new()
	assert(restored.load_dict(JSON.parse_string(JSON.stringify(ada.to_dict()))))
	var bad := ada.to_dict()
	bad.age = 17
	assert(not restored.load_dict(bad) and restored.to_dict()==ada.to_dict())
	bad = Ada.new().to_dict()
	bad.recruitment = "recruited"
	assert(not restored.load_dict(bad))
	print("ADA COMPANION PASS: repair before invitation, acceptance, one reward, adult identity, atomic save")
	quit()
