"""Offline production browser for the real extracted character sprites."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
BANK = ROOT / 'kits/character-families'
catalog = json.loads((BANK / 'catalog.json').read_text())
roster = json.loads((BANK / 'preview-roster.json').read_text())
payload = json.dumps({'catalog': catalog, 'roster': roster}, ensure_ascii=True).replace('</', '<\\/')
page = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cattle Trail â€” Character Workshop</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#201b17;color:#f4dfb5;font:16px system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:28px}h1{font-family:Georgia,serif;margin:0 0 10px}p{line-height:1.6;max-width:900px}header{border-bottom:1px solid #6c5136;padding-bottom:20px}button,input{font:inherit;color:inherit;background:#35291e;border:1px solid #926e42;border-radius:6px;padding:10px 15px}button{cursor:pointer}button[aria-pressed=true]{background:#a06831;color:#fff7df}nav{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}.masters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.master{margin:0}.master img{width:100%;height:300px;object-fit:contain;background:#120f0d}.master figcaption{padding:10px 0}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px}.card{background:#30251b;border:1px solid #70502f;border-radius:8px;padding:12px;min-width:0}.sprite{width:128px;height:128px;image-rendering:pixelated;background-repeat:no-repeat;margin:auto}.card strong{display:block;margin:8px 0 5px}.card small{display:block;color:#d5b98c;line-height:1.5}.badge{font-size:12px;color:#f4ba76}details{margin:16px 0 28px}summary{cursor:pointer;padding:10px 0}footer{margin-top:30px;color:#b49b7c}a{color:#efbd72}@media(max-width:700px){main{padding:16px}.masters{grid-template-columns:1fr}.master img{height:auto}}
</style><main><header><h1>Cattle Trail Â· Character Workshop</h1><p id="count"></p><p>Whole-character families with confident frontier wardrobes, distinct faces and practical equipment. These are static identity candidates. Each selected character gets its own movement and action kit next.</p></header>
<details open><summary>Three master references</summary><section class="masters" id="masters"></section></details>
<nav aria-label="Character family"><button data-family="all" aria-pressed="true">All characters</button><button data-family="rancher" aria-pressed="false">Ranchers</button><button data-family="mechanic" aria-pressed="false">Mechanics</button><button data-family="spirit-scout" aria-pressed="false">Spirit scouts</button><input id="search" aria-label="Search characters" placeholder="Name or personality"></nav>
<section class="grid" id="grid" aria-live="polite"></section><footer>Production browser Â· real transparent atlases Â· hard pixel enlargement Â· no game launch required. <a href="catalog.json">Sprite metadata</a> Â· <a href="preview-roster.json">Character records</a></footer></main>
<script>const DATA=__DATA__;
const labels={'rancher':'Eleanor-derived frontier master','mechanic':'Ada Mercer Â· mechanic master','spirit-scout':'Ines Vale Â· spirit-scout master'};
const local=p=>p.replace('res://','').replace('kits/character-families/','');
document.querySelector('#count').textContent=`${DATA.catalog.counts.master_images} detailed master references Â· ${DATA.catalog.counts.static_variants} extracted character variants Â· ${DATA.catalog.counts.batches} batches`;
const seen=new Set();for(const f of DATA.catalog.families){if(seen.has(f.master_sha256))continue;seen.add(f.master_sha256);const fig=document.createElement('figure');fig.className='master';const img=document.createElement('img');img.src=local(f.master_image);img.alt=labels[f.id.replace('-batch02','')]||f.id;const cap=document.createElement('figcaption');cap.textContent=img.alt;fig.append(img,cap);document.querySelector('#masters').append(fig);}
let selected='all';function draw(){const grid=document.querySelector('#grid');grid.replaceChildren();const term=document.querySelector('#search').value.toLowerCase();for(const c of DATA.roster.characters){if(selected!=='all'&&c.family!==selected)continue;if(!(c.name+' '+c.temperament+' '+c.art_id).toLowerCase().includes(term))continue;const card=document.createElement('article');card.className='card';const sprite=document.createElement('div');sprite.className='sprite';sprite.setAttribute('role','img');sprite.setAttribute('aria-label',`${c.name}, adult ${c.family}`);sprite.style.backgroundImage=`url("${local(c.sprite.atlas)}")`;sprite.style.backgroundSize='512px 512px';sprite.style.backgroundPosition=`${-2*c.sprite.rect[0]}px ${-2*c.sprite.rect[1]}px`;const title=document.createElement('strong');title.textContent=c.name;const detail=document.createElement('small');detail.textContent=`Age ${c.age} Â· ${c.temperament}`;const id=document.createElement('small');id.textContent=c.art_id;const badge=document.createElement('span');badge.className='badge';badge.textContent='Static candidate';card.append(sprite,title,detail,id,badge);grid.append(card);}}
for(const button of document.querySelectorAll('button[data-family]'))button.onclick=()=>{selected=button.dataset.family;for(const b of document.querySelectorAll('button[data-family]'))b.setAttribute('aria-pressed',String(b===button));draw();};document.querySelector('#search').oninput=draw;draw();</script></html>'''
(BANK / 'index.html').write_text(page.replace('__DATA__', payload), encoding='utf-8')
print(f"CHARACTER GALLERY BUILT: {len(roster['characters'])} real sprite cards, family filters and master references")
