extends SceneTree
const Adventure = preload("res://scripts/lantern_adventure.gd")
const Presentation = preload("res://scripts/lantern_presentation.gd")

func _initialize() -> void:
	var a := Adventure.new()
	assert(not Presentation.describe(a).spirit_visible)
	a.begin(true,false,["a","b","c"])
	var before := a.to_dict()
	var view := Presentation.describe(a)
	assert(view.spirit_visible and view.carry_lantern and view.spirit_clip=="agitated")
	assert(a.to_dict()==before,"Presentation cannot change gameplay progress")
	a.settle_spirit()
	assert(Presentation.describe(a).spirit_clip=="listening")
	a.begin_guiding()
	a.guide_cattle("a")
	a.pause()
	view = Presentation.describe(a)
	assert(view.can_resume and not view.carry_lantern and view.guided_count==1)
	var restored := Adventure.new()
	assert(restored.load_dict(JSON.parse_string(JSON.stringify(a.to_dict()))))
	assert(Presentation.describe(restored)==view,"Loading reconstructs identical presentation without replaying events")
	restored.resume(true)
	restored.fail()
	assert(Presentation.describe(restored).can_retry)
	restored.retry(true)
	restored.guide_cattle("b")
	restored.guide_cattle("c")
	assert(Presentation.describe(restored).spirit_clip=="settled")
	restored.finish_at_wagon(true)
	assert(Presentation.describe(restored).show_completion and not Presentation.describe(restored).carry_lantern)
	print("LANTERN PRESENTATION PASS: checkpoint views, pause and retry, immutable state, restore parity")
	quit()
